#+title: Transcription of (Toronto) Councillor Josh Matlow's Deputation on Hamilton's LRT
#+author: Connor Feeley
#+date: 2024-01-30

Transcribed from [[https://youtu.be/5-xithlJT6I?t=2327][Light Rail Transit Sub-Committee - January 29, 2024 - YouTube]], from around the 38:47 mark.

* Councillor Nrinder Naan (Chair)
First up we have Councillor Josh Matlow City of Toronto respecting the Hamilton LRT.

Welcome Josh. We have a five-minute rule at the four-minute mark you'll hear a ding which indicates to you that you have 60 seconds remaining.

At this point if you could turn on your camera and microphone so we can we had seen you earlier and I just want to make sure we can hear you.

Hi. Please proceed.

* (Toronto) Councillor Josh Matlow
Well thank you. Thank you chair and members for having me today to share some experiences that we've had in Toronto that I believe would be informative and hopefully helpful as you consider an incredibly important decision that will impact not only the future of transit in Hamilton but the service that I know all of you want to deliver to the residents that you serve.

I've had conversations with your local ATU 107 and HSR and I've learned about what you are deciding.

And I want to make it very clear that  the lessons that I'm sharing with you and the experiences that we've had in Toronto are simply to contribute to your consideration.

Ultimately it is yours to make and it is your city to serve.

But from our experience as attractive as potential cost savings might be, I would ask you to consider the long-term cost of sacrificing your ability to  provide direct oversight and demand accountability for the residents you serve.

I submit to you that it would be huge.

And we've seen that in Toronto along the Eglinton line.

I represent a community along Eglinton.

And I can tell you, you know, about a decade ago I was open to the idea of a P3, a private-public partnership.

I didn't come into it from an ideological lens.

And I certainly... the idea of cost savings is attractive and I recognize that.

But I'm no longer considering P3s from a hypothetical.

I'm coming to it from real-life experience.

It was promised through the design and construction of the Eglinton Metrolinx LRT  that not only would any risks, including cost overruns and delays, be taken on by the private consortium that Metrolinx hired.

Our experience has been that the cost has ballooned over a billion dollars.

There have been delays since 2020 that have had an enormous adverse impact on local residents' quality of life and businesses along the line.

Our ability as local councillors, and I hope this will be helpful to those of you who are elected to serve Hamiltonians, has been that any time we hear concerns from our residents, yes, we can speak up, we can advocate.

But unlike at the TTC, where as a commissioner at the TTC, I'm able to go to the board, advocate, demand accountability, move motions to try to fix things and find solutions.

Given that it is a private company working [through] Metrolinx, we can simply ask, but they can ignore.

And that happens time and time again.

The secrecy and the lack of transparency by Metrolinx and their consortium  has also made it incredibly difficult to even understand why problems happen and why delays have occurred.

In fact, Phil Verster - the CEO of Metrolinx - has made, has done press conferences to simply announce that he could not announce anything to do with why the delays have happened.

If it wasn't so serious, it would have been satirical.

We also supported an integrated transit network in Toronto.

In other words, our TTC will be running the operations of our new LRTs.

And while Waterloo, I know, has had a very different experience on the ION line,  they are more of a regional line serving a regional area.

I would submit to you that your line in Hamilton will act more like a municipal spine to the heart of your city.

From Eastgate to McMaster.

And ultimately, all of those 14 kilometres will serve to feed various bus routes.

If there are any conflicts and decisions between a third party and HSR, that could end up with serious impacts on the service that you deliver to residents.

Now, we've had experiences in Toronto, for example, with our Astral Media contract,  which provides furnishings for bus shelters, garbage cans, etc.

Years ago, that seemed attractive, too.

It seemed like a great idea.

What we've experienced now is that it's impossible to get things fixed.

There are delays in getting even doors fixed on garbage cans.

And the experience we've had is that if we don't have a direct oversight and accountability, as local councillors, we can't provide the service that our constituents expect.

I'll conclude by offering this:

We hear things from Metrolinx and their consortium.

But they don't really consult with us.

Their consortium, the private companies, have actually sued Metrolink successfully several times.

We theorize, because we haven't had details shared with us, that that also could be, those conflicts could be a cause of the delays that we've experienced [since 2020] to even see the line on Eglinton open.

* Councillor Nrinder Naan (Chair)
Thank you.

I'm going to have to interrupt you there as you've reached your five-minute timeline.

I'm not sure if you could hear the four-minute marker bell.

So at this point, I'm going to have to ask you to pause there.

If any of the councillors have any questions, perhaps the remainder of what you were hoping to say could be in the responses to committee members' questions around the table.

So opening it up for questions to our delegate.

Member Andrus.

* Member Andrus
I wanted to ask you:

Why did Toronto choose to keep the operations in-house versus the design, build, finance, operate, maintain model  that Hamilton is looking at with only Bundle 3, the passenger interface, being looked at today by the staff recommendation?  Can I ask you what the choice was to keep those operations in-house?

* (Toronto) Councillor Josh Matlow
The [inaudible] is, for a number of reasons.

The foremost is that we want an integrated operation of our transit system. Your Hamilton LRT will serve in some ways like our Eglinton line along [with?] the subway.

It has to interact on a daily basis with all the other service routes.

And we wouldn't want to have different bodies making different decisions possibly in conflict with each other.

So it makes a lot of sense just from a functional perspective to have the TTC operate the system.

Now, ultimately, we also, you know, whatever cost savings might be most like, it was with us years ago.

We also wouldn't want to see us compromising or Metrolinx in this case compromising the labor standards or service delivery.

And then lastly, as I mentioned about [inaudible; "service"?] accountability.

I as a councillor - and I imagine the councillors on this committee would feel the same way - I have the ability when the TTC does something good to encourage and support them.

And when they do something that is a mistake. I have the ability to [inaudible], and then propose solutions that we can actually implement on the ground here in the city of Toronto, rather than hope that Metrolinx or their private company will consider our request.

* Member Andrus
Thank you.

Quick follow-up.

So the Finch West LRT line is actually nearing completion; possibly be completed before the Eglinton Crosstown line.

That one was also chosen for operations to be kept in house with the TTC.

And that line, of course, is much closer - being all surface rail with no tunneling - to the Hamilton LRT project.

Can you speak a little bit about that project? And what the difference has been in the experience? You talked a little bit about Eglinton being a black box.

But could you talk a little bit about your experience with the Finch West?  I think it's a little bit closer to our project.

* (Toronto) Councillor Josh Matlow
Well, Finch West certainly has been relatively a smoother experience.

That being said, there's still, and if you speak to the local councillors along Finch.

There's still been challenges to get regular information that's helpful to the communities.

And, you know, ultimately, what I think all of us share on the Toronto City Council is an interest in being able to advocate for our constituents, have access to information, hold our service deliverers, in this case, our staff, accountable for decisions that are made, and the way that they provide service, and then also to be able to move motions.

Not asking Metrolinx or the provincial government to do something - be able to actually do something here on the ground to serve our residents.

And while Finch, yes, the construction design has been smoother than the Eglinton line, ultimately, they will be operated by the TTC.

And that's the decision that you're going to have to make as [inaudible].

* Member Andrus
Thank you.

Last quick question from me.

So on that operations:

What do you expect once you assume those operations through the TTC as a city?  Once the handoff - I especially think of Finch West because it's the most applicable to our project - when that handoff is complete (and it seems to have less issues than the Eglinton Crosstown), what do you expect to change in the relationship with both the service delivery and the project itself?

* (Toronto) Councillor Josh Matlow
It'll be refreshing, thankfully, to have the operations entirely done by the TTC.

These are publicly accountable employees.

These are people who actually [inaudible; "report to and"?] answer to the TTC [board], where city councillors along with citizens sit.

And we will have the ability to work with the TTC and their staff to be able to manage a holistic integrated system.

We've had recent experiences, even a week ago, on Eglinton as part of the design and construction phase.

Where it wasn't even Metrolinx that made the decision to shut down an intersection.

Even blocked access.

[inaudible]

* Councillor Nrinder Naan (Chair)
Sorry, you cut out there.

Your feed is cutting out a little bit.

You cut out right at "the intersection".

* (Toronto) Councillor Josh Matlow
There was an intersection, a duplex at Eglinton.

[inaudible] the area.

That was shut down by Crosslinx, which is the private consortium, the third party, that's constructing the Edmonton line.

They did it unilaterally.

It wasn't even Metrolinx.

They didn't [inaudible] Metrolinx.

[inaudible]

But we found out after the fact, is that not only did they block an intersection to businesses and residents.

But they even blocked access to the police station which is at the corner of that intersection.

The challenge that that presented, and the reason why I look forward to the TTC being able to operate the entire system, is because they did things unilaterally, and they're not accountable to us.

The TTC will be not only accountable, but we actually have a say in their operations.

Which I think will be incredibly helpful.

* Councillor Nrinder Naan (Chair)
Thank you Member Andrus.

Any further questions for our delegate?  Oh.

Next up is Councillor Maureen Wilson.

Followed by Councillor Danko.

* Councillor Maureen Wilson
Thank you, Chair.

Just a question of clarification.

Just trying to follow the logic that the Waterloo experience is somehow different because it's a regional line.

I'm not sure I understand.

If I could just get some further insight, that would be helpful.

* (Toronto) Councillor Josh Matlow
Yeah [ION].

It's a regional line that serves the Waterloo region.

The way that the Hamilton line will function and operate and serve, I would submit to you is more similar to Toronto's subway, Eglinton, and yes, Finch, lines.

The lines that serve through the spine of our city.

And that have the local [inaudible].

In our case [inaudible].

That will feed into the spines of our transit.

So, the idea being [inaudible].

[inaudible]

* Councillor Nrinder Naan (Chair)
You're breaking up again.

And I apologize.

So, we're not able to hear you clearly.

I wonder if you can take off your video feed.

So, we can focus on your audio only.

And then that way you can be heard more clearly.

Let's try that out.

[back and forth as Matlow tests his microphone]

If I could.

Councillor Wilson.

To what point did you hear clearly?

* Councillor Maureen Wilson
I think, Chair, I heard clearly up until the point that the distinction - and I don't want to put these words into [his mouth].

So, I'm just looking for confirmation.

The distinction is that Hamilton's LRT is running through an urban center as opposed to the Waterloo experience.

But I'm not sure.

* (Toronto) Councillor Josh Matlow
No, thank you.

It isn't so much [inaudible].

It's the way that it functions [inaudible].

In other words, because there are so many local, and in your case HSR operated bus routes that will connect to, as I described, each spine of your transit network, once the LRT is completed.

That it just -

I would say [inaudible].

... difficult for you in the future if you have one body operating the buses that feed into the LRT.

And then a third party - arms length, private company, that's operating the Hamilton LRT.

Now, if they are always working well together, and they're always on the same page, that might be a better experience.

I think it's fair to guess [inaudible].

* Councillor Nrinder Naan (Chair)
Still really hard to hear you, Councillor Matlow.

We did get enough of a response to your last question.

Councillor Wilson is satisfied with your response.

Next up we have Councillor Danko.

And I'm not sure if there's anything else you can do on your end to optimize your feed.

And I'll turn to the clerks... if there's anything else we can suggest.

* Councillor John-Paul Danko
Actually, Chair, I'd think with the former Roger's CEO as a Mayor of Toronto they'd have better internet.

I'll reserve my questions. I'll ask staff.

Thank you.
